#!/bin/bash

rm -rvf build
rm -rvf world
rm -rvf us
rm -rvf germany

mkdir -p build

world_shp() {
  mkdir -p world
  curl -z build/ne_$1_admin_0_countries.zip -o build/ne_$1_admin_0_countries.zip http://naciscdn.org/naturalearth/$1/cultural/ne_$1_admin_0_countries.zip
  unzip -od build build/ne_$1_admin_0_countries.zip
  chmod a-x build/ne_$1_admin_0_countries.*
}

# britain_shp() {}

germany_shp() {
  mkdir -p germany
  dir=vg250_0101.utm32s.shape.kompakt/vg250_kompakt
  curl -o build/vg250_utm32s.zip http://sg.geodatenzentrum.de/web_download/vg/vg250_0101/utm32s/shape/vg250_0101.utm32s.shape.kompakt.zip
  unzip -ojd build build/vg250_utm32s.zip $dir/VG250_F.cpg $dir/VG250_F.dbf $dir/VG250_F.prj $dir/VG250_F.shp $dir/VG250_F.shx
  chmod a-x build/VG250_F.*
}

us_shp() {
  mkdir -p us
  curl -o build/cb_2015_us_county_5m.zip 'https://www2.census.gov/geo/tiger/GENZ2015/shp/cb_2015_us_county_5m.zip'
  unzip -od build build/cb_2015_us_county_5m.zip cb_2015_us_county_5m.shp cb_2015_us_county_5m.dbf
  chmod a-x build/cb_2015_us_county_5m.*
}

world() {
  world_shp $1
  mkdir -p world
  geo2topo -q 1e5 -n countries=<( \
      shp2json -n build/ne_$1_admin_0_countries.shp \
        | ndjson-map '(d.id = d.properties.iso_n3, d)' \
        | geostitch -n) \
    | topomerge land=countries \
    > world/$1.json
  shp2json -n build/ne_$1_admin_0_countries.shp \
    | ndjson-map 'd.properties' \
    | ndjson-sort 'a.iso_a3.localeCompare(b.iso_a3)' \
    | json2tsv -n \
    > world/$1.tsv
}

germany() {
  germany_shp
  geo2topo -q 1e5 -n regions=<( \
    shp2json -n build/VG250_F.shp \
      | ndjson-filter '!/000$/.test(d.properties.RS)' \
      | ndjson-map '(d.id = d.properties.RS, d)') \
    | toposimplify -f -p 0.25 \
  > germany/250m--regions.json
}

us() {
  us_shp
  geo2topo -q 1e5 -n counties=<( \
      shp2json -n build/cb_2015_us_county_5m.shp \
        | ndjson-filter '!/000$/.test(d.properties.GEOID)' \
        | ndjson-map '(d.id = d.properties.GEOID, d)' \
        | geoproject -n 'd3.geoAlbersUsa().scale(1280).translate([480, 300])') \
    | toposimplify -f -p 0.25 \
    | topomerge states=counties -k 'd.id.slice(0, 2)' \
    | topomerge nation=states \
    > us/10m.json
}

world 110m
world 50m
us
germany
